### ISSUE TITLE
Feature Request: allow await in the filter expression of a catch clause

### ISSUE THREAD

**Issue by BigBadBleuCheese** [dotnet/csharplang#1199]
Currently, an attempt to await in the filter expression of a catch clause will result in:

```
Error CS7094: Cannot await in the filter expression of a catch clause
```

I understand (and grant) that is certainly not a good idea to do this in just about any case and many features of the design of C# are intended to prevent bad practices. However, there are cases in which such awaiting is warranted (for example, there is not a synchronous version of a given API). In such cases, the language currently only leaves the programmer with less than optimal alternatives:

* getting the value of `Task<T>.Result` and thereby blocking the caller
* incorporating the asynchronous element of the filter at the beginning of the catch block and throwing again if it is not met and thereby overcomplicating the inner exception list (or wiping out the original stack trace in the case of a novice programmer throwing what they caught)

**Comment by yaakov-h** [comment]
Is this even possible with the current CLR?

**Comment by BigBadBleuCheese** [comment]
It is totally possible that it is not and that I’ve made this request in the wrong place.

**Comment by jnm2** [comment]
Unless the CLR is changed so that exception handling is not synchronous, it's a very good thing that that language exposes what's really going on à la `.GetAwater().GetResult()` or (`.Result`, which is usually not what you want if the method is an async state machine.)

**Comment by jnm2** [comment]
Meanwhile... there's got to be a cleaner way to achieve the same end goal without filtering exceptions based on an IO-bound or long-running procedure.

**Comment by HaloFour** [comment]
I think that it would be doable but it would involve the compiler writing its own implementation of the exception filter rather than using the CLR feature.  It probably wouldn't be that dissimilar to how C# handles `await` within a `catch` block today.

**Comment by jnm2** [comment]
@HaloFour How would that interop with already-compiled assemblies today without trashing the stack trace?

**Comment by HaloFour** [comment]
@jnm2 

C# uses the [ExceptionDispatchInfo](https://msdn.microsoft.com/en-us/library/system.runtime.exceptionservices.exceptiondispatchinfo(v=vs.110).aspx) class to manage rethrowing now with async catch blocks.

**Comment by jnm2** [comment]
@HaloFour OP explicitly asked to avoid that:

> thereby overcomplicating the inner exception list

**Comment by HaloFour** [comment]
@jnm2 

I'm not currently in front of VS to see what happens when you use that, but given this is what C# does today in order to handle `await` within a `catch` block I imagine that a hypothetical `await` within a `catch` filter would behave in the same way.  IIRC the entire point of `ExceptionDispatchInfo` is not to screw up the original call stack of the exception.

**Comment by BigBadBleuCheese** [comment]
So, should I be making this request elsewhere (i.e. as a change to the CLR)? If so, where?

**Comment by sharwell** [comment]
This would not be possible without major changes in the CLR. Exception filters are evaluated _before_ unwinding the stack, so implementing this is equivalent to allowing a runtime-inserted `await` anywhere an exception can be thrown, even in methods that are not `async`.
